# AWS Data Lake Framework Configuration

# AWS Configuration
aws:
  region: us-east-1
  profile: default

# S3 Configuration
s3:
  bronze_bucket: datalake-bronze
  silver_bucket: datalake-silver
  prefix: data
  
# S3Tables Configuration
s3tables:
  database_name: datalake_silver
  catalog_id: ""  # Leave empty to use the default AWS account

# Glue Configuration
glue:
  job_timeout: 2880  # minutes
  worker_type: G.1X
  number_of_workers: 5
  max_concurrent_runs: 1
  
# Data Configuration
data:
  date_format: "%Y-%m-%d"
  timestamp_format: "%Y-%m-%d %H:%M:%S"
  
# Logging Configuration
logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
# Environment
environment: development  # development, staging, production
